"""Add azure_hybrid_benefit and currency fields

Revision ID: 102d8f6ac9b9
Revises: 
Create Date: 2026-03-10 19:07:13.666319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '102d8f6ac9b9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bill_of_materials', sa.Column('azure_hybrid_benefit', sa.Boolean(), nullable=False))
    op.add_column('bill_of_materials', sa.Column('currency', sa.String(length=10), nullable=False))
    op.drop_column('bill_of_materials', 'description')
    op.drop_column('bill_of_materials', 'created_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bill_of_materials', sa.Column('created_by', sa.VARCHAR(length=100), nullable=True))
    op.add_column('bill_of_materials', sa.Column('description', sa.TEXT(), nullable=True))
    op.drop_column('bill_of_materials', 'currency')
    op.drop_column('bill_of_materials', 'azure_hybrid_benefit')
    # ### end Alembic commands ###
